// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Detect if running a migration or DB schema command to use DIRECT_URL, otherwise default to DATABASE_URL
const isDbCommand = process.argv.some(arg => arg.includes("migrate") || arg.includes("db") || arg.includes("push"));
const dbUrl = isDbCommand 
  ? (process.env["DIRECT_URL"] || process.env["DATABASE_URL"]) 
  : process.env["DATABASE_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: dbUrl,
  },
});
